#ifndef _MOBEFFECT_H
#define _MOBEFFECT_H

//This header template file is generated by Disassembler.

class MobEffect {
	public:
    //Fields
    char filler_MobEffect[UNKNOW_SIZE];
	public:
    //Virtual Tables
	virtual ~MobEffect();
	virtual void applyEffects(Actor*, int, int) const;
	virtual void removeEffects(Actor*);
	virtual void applyInstantaneousEffect(Actor*, Actor*, Actor*, int, float) const;
	virtual void isInstantaneous() const;
	virtual void getAttributeModifierValue(int, AttributeModifier const&) const;
	public:
    //Methods
    MobEffect(int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool, int, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool);
    void shutdownEffects();
    void _createTemporalBuff(AttributeBuff const&, int, int) const;
    void clearAttributeBuffs();
    void getComponentName() const;
    void getColor() const;
    void getIcon() const;
    void isVisible() const;
    void addAttributeModifier(Attribute const&, std::__ndk1::shared_ptr<AttributeModifier>);
    void clearAttributeModifiers();
    void setDurationAmplifier(std::__ndk1::shared_ptr<Amplifier>);
    void addAttributeBuff(Attribute const&, std::__ndk1::shared_ptr<AttributeBuff>);
    void getDescriptionId() const;
    void isDisabled() const;
    void viewAttributeModifiers() const;
    void getId() const;
    void _createInstantBuff(AttributeBuff const&, int, float) const;
    void setValueAmplifier(std::__ndk1::shared_ptr<Amplifier>);
    void getDurationModifier() const;
    void getIconName() const;
    void hasIcon() const;
    void formatDuration(MobEffectInstance const*);
    void initEffects(ResourcePackManager*);
    void _createAttributeModifer(AttributeModifier const&, int) const;
    void getByName(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&);
    void isHarmful() const;
    void getResourceName() const;
    void getById(int);
	public:
    //Objects
    static MobEffect** mMobEffects;
    
    static MobEffect* DAMAGE_RESISTANCE;
    static MobEffect* HEALTH_BOOST;
    static MobEffect* HUNGER;
    static MobEffect* BAD_OMEN;
    static MobEffect* WEAKNESS;
    static MobEffect* WITHER;
    static MobEffect* NIGHT_VISION;
    static MobEffect* MOVEMENT_SLOWDOWN;
    static MobEffect* WATER_BREATHING;
    static MobEffect* CONDUIT_POWER;
    static MobEffect* ABSORPTION;
    static MobEffect* REGENERATION;
    static MobEffect* HEAL;
    static MobEffect* SATURATION;
    static MobEffect* LEVITATION;
    static MobEffect* DEFAULT_COLOR;
    static MobEffect* FIRE_RESISTANCE;
    static MobEffect* JUMP;
    static MobEffect* EMPTY_EFFECT;
    static MobEffect* HERO_OF_THE_VILLAGE;
    static MobEffect* POISON;
    static MobEffect* DIG_SLOWDOWN;
    static MobEffect* DIG_SPEED;
    static MobEffect* DAMAGE_BOOST;
    static MobEffect* CONFUSION;
    static MobEffect* MOVEMENT_SPEED;
    static MobEffect* SLOW_FALLING;
    static MobEffect* BLINDNESS;
    static MobEffect* FATAL_POISON;
    static MobEffect* INVISIBILITY;
    static MobEffect* HARM;
};//MobEffect

#endif // _MOBEFFECT_H
